[package]
name = "openapi"
version = "0.1.5"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Rust bindings for openapi schemas"
documentation = "https://softprops.github.io/openapi"
homepage = "https://github.com/softprops/openapi"
repository = "https://github.com/softprops/openapi"
keywords = ["openapi", "swagger"]
license = "MIT"

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.8"
failure = "0.1"
semver = "0.9"
url = "1"
url_serde = "0.2"
